Feature/#9 Comment Entity 생성
kgu-developers/aics-server pull request #13
Opened 2024-10-18 14:05 UTC by minjo-on

## Summary

> close #9 

## Tasks

작업 내용: Comment 엔티티 구현

댓글(Comment) 엔티티를 정의하여 댓글 정보를 관리할 수 있도록 함.
id, content, author(작성자) 필드를 포함하여 댓글의 기본 정보를 저장.
BaseTimeEntity를 상속받아 생성일과 수정일을 자동으로 관리.
필드 및 관계 설정

id: 댓글의 고유 식별자.
content: 댓글의 내용 필드, nullable = false로 설정하여 필수 입력 항목으로 지정.
author: 댓글 작성자를 User 엔티티와 연관시킴. ManyToOne 관계로 설정, 지연 로딩(Lazy Loading)을 사용하여 작성자 정보를 필요할 때만 가져오도록 처리.
정적 팩토리 메서드 제공

Comment.create(String content, User author) 메서드를 통해 댓글 생성 시 간편하게 작성자와 내용을 설정할 수 있도록 함.

추가 작업 예정:
Post 엔티티와의 관계 설정은 주석 처리됨. 이후 필요시 활성화하여 댓글이 어느 게시글에 속해 있는지 관리할 예정.
추후에 서비스 레이어 개발 시 메소드 추가 예정

## To Reviewer

빠트린거나 불편한거 언제든지 말씀해주세용

2024-10-18 15:01 UTC, LeeShinHaeng reviewed
깔끔하고 정확한것 같아요 👍

2024-10-19 04:52 UTC, LeeHanEum requested changes
완벽합니다! 그런데 tab 간격이 조금 다른거 같아요.
인텔리제이 설정에서 tab 간격을 4로 변경해서 커밋 부탁드릴께요~
<img width="1094" alt="스크린샷 2024-10-19 오후 1 51 52" src="https://github.com/user-attachments/assets/6524737e-e240-4bdc-8c8a-3b50a2d25705">

2024-10-19 04:52 UTC, LeeHanEum commented on aics-core/aics-domain/src/main/java/kgu/developers/core/domain/comment/Comment.java
> +	}
추후 `post` 객체를 매개변수로 받을 수 있도록 주석 하나 달아놓아주시면 좋을거 같아요.
`// TODO : ~~~`

2024-10-19 06:06 UTC, LeeHanEum approved these changes
👍

2024-10-19 07:48 UTC, merged