feature/#16 전공 생성 API
kgu-developers/aics-server pull request #22
Opened 2024-10-20 14:15 UTC by LeeShinHaeng

## Summary

> close #16 

## Tasks

- 전공 생성 엔드포인트 생성
- 전공 생성 로직 및 중복 검사 로직 작성
- 전공 영속성 관련 구현
- 전공 생성을 위한 DTO 작성
- 중복, NotFound에 대한 Exception 생성

## To Reviewer

처음 해보는 구조라 여기저기 참고하긴했지만 부족한 부분이 많습니다.
많이 지적해주시길 바랍니다!!

2024-10-20 14:51 UTC, LeeHanEum requested changes
많이 고민하신 흔적이 보여요 👍👍
코드 리뷰 한 내용 고려해주셔서 수정해주시면 감사하겠습니다!!

2024-10-20 14:51 UTC, LeeHanEum commented on aics-apis/aics-api/src/main/java/kgu/developers/apis/api/major/presentation/request/MajorCreateRequest.java
> +    @NonNull
`@NotNull`이 아닌 NPE를 발생시키는 `@NonNull`을 쓰신 이유가 있을까요?

2024-10-20 14:51 UTC, LeeHanEum commented on aics-apis/aics-api/src/main/java/kgu/developers/apis/api/major/presentation/request/MajorCreateRequest.java
> +    @Length(min = 1, max = 10)
`@Length` 어노테이션은 하이버네이트에 종속적이라는 단점이 있는데요, `@Size` 어노테이션을 대신 쓰는걸 조심스럽게 제안드려봅니다 👍

2024-10-20 14:51 UTC, LeeHanEum commented on aics-apis/aics-api/src/main/java/kgu/developers/apis/api/major/presentation/response/MajorPersistResponse.java
> +    public static MajorPersistResponse from(Major major) {
객체 지향적인 관점에서 저는 MajorPersistResponse가 Major 객체를 알 필요는 없다고 생각합니다.
Long id를 매개변수로 받는 정적 팩토리 메서드 of를 사용하는 건 어떻게 생각하시나요?

2024-10-20 14:51 UTC, LeeHanEum commented on aics-apis/aics-api/src/main/java/kgu/developers/apis/api/major/presentation/exception/MajorExceptionCode.java
> +    MAJOR_NOT_FOUND(HttpStatus.NOT_FOUND, "확인되지 않는 전공입니다."),
static import 해주시면 더 깔끔할거 같아요!

2024-10-20 14:51 UTC, LeeHanEum commented on aics-apis/aics-api/src/main/java/kgu/developers/apis/api/major/presentation/MajorController.java
> +    @PostMapping("/create")
1. Swagger에 API에 대한 설명을 추가하는 `@Operation`, `@ApiResponses` 어노테이션을 추가하면 어떨까요?
2. major 도메인에서는 API 개수가 적을것 같아요. 불필요한 `create` 키워드 없이 더 간결하게 `/api/v1/major` 로 처리하는건 어떨까요?

2024-10-20 14:51 UTC, LeeHanEum commented on aics-apis/aics-api/src/main/java/kgu/developers/apis/api/major/presentation/MajorController.java
> +    public MajorPersistResponse createMajor(@RequestBody MajorCreateRequest request) {
Controller단에서 리턴 타입에는 `ResponseEntity`를 사용해야 합니다!

[Controller 예시 코드 참고](https://github.com/depromeet/moring-server/blob/develop/moring-api/src/main/java/org/depromeet/sambad/moring/api/event/EventController.java)

2024-10-20 14:51 UTC, LeeHanEum commented on aics-apis/aics-api/src/main/java/kgu/developers/apis/api/major/application/MajorService.java
> +        }
중복인지 확인하는 로직이니까 findByName 보다는 existsByName이 더 적절해 보입니다!

2024-10-20 15:14 UTC, LeeShinHaeng commented on aics-apis/aics-api/src/main/java/kgu/developers/apis/api/major/presentation/request/MajorCreateRequest.java
> +    @NonNull
NotNull이 더 이점이 많군요! 감사합니다
[9ececfa](https://github.com/kgu-developers/aics-server/pull/22/commits/9ececfa535ec59d4af4bc647ff634f205818236f) 에서 반영했습니다!!

2024-10-20 15:15 UTC, LeeShinHaeng commented on aics-apis/aics-api/src/main/java/kgu/developers/apis/api/major/presentation/request/MajorCreateRequest.java
> +    @Length(min = 1, max = 10)
종속성을 최대한 줄이는게 좋지요 좋은 의견 감사합니다.
[9ececfa](https://github.com/kgu-developers/aics-server/pull/22/commits/9ececfa535ec59d4af4bc647ff634f205818236f)에서 반영 했습니다!

2024-10-20 15:15 UTC, LeeShinHaeng commented on aics-apis/aics-api/src/main/java/kgu/developers/apis/api/major/presentation/response/MajorPersistResponse.java
> +    public static MajorPersistResponse from(Major major) {
동의합니다!
[9ececfa](https://github.com/kgu-developers/aics-server/pull/22/commits/9ececfa535ec59d4af4bc647ff634f205818236f)에서 반영 했습니다!!

2024-10-20 15:15 UTC, LeeShinHaeng commented on aics-apis/aics-api/src/main/java/kgu/developers/apis/api/major/presentation/exception/MajorExceptionCode.java
> +    MAJOR_NOT_FOUND(HttpStatus.NOT_FOUND, "확인되지 않는 전공입니다."),
넵~~
[9ececfa](https://github.com/kgu-developers/aics-server/pull/22/commits/9ececfa535ec59d4af4bc647ff634f205818236f)에서 반영 했습니다!

2024-10-20 15:16 UTC, LeeShinHaeng commented on aics-apis/aics-api/src/main/java/kgu/developers/apis/api/major/presentation/MajorController.java
> +    @PostMapping("/create")
좋습니다
[9ececfa](https://github.com/kgu-developers/aics-server/pull/22/commits/9ececfa535ec59d4af4bc647ff634f205818236f)에서 반영 했습니다!

2024-10-20 15:16 UTC, LeeShinHaeng commented on aics-apis/aics-api/src/main/java/kgu/developers/apis/api/major/presentation/MajorController.java
> +    public MajorPersistResponse createMajor(@RequestBody MajorCreateRequest request) {
앗 제가 깜빡했네요
[9ececfa](https://github.com/kgu-developers/aics-server/pull/22/commits/9ececfa535ec59d4af4bc647ff634f205818236f)에서 반영 했습니다!!

2024-10-20 15:18 UTC, LeeShinHaeng commented on aics-apis/aics-api/src/main/java/kgu/developers/apis/api/major/application/MajorService.java
> +        }
그게 더 성능과 가독성 차원에서 좋을것 같습니다. 동의합니다.
[9ececfa](https://github.com/kgu-developers/aics-server/pull/22/commits/9ececfa535ec59d4af4bc647ff634f205818236f)에서 반영 했습니다!

2024-10-20 15:30 UTC, LeeHanEum reviewed
2가지만 마지막으로 한번 더 확인 부탁드립니다!
제 의도와 다르게 전달된거 같아요 ㅠ

2024-10-20 15:30 UTC, LeeHanEum commented on aics-apis/aics-api/src/main/java/kgu/developers/apis/api/AicsApiApplication.java
> +    }
요거 들여쓰기 문제 있는거 같은데 확인 한번 해주세요~

2024-10-20 15:30 UTC, LeeHanEum commented on aics-apis/aics-api/src/main/java/kgu/developers/apis/api/major/presentation/response/MajorPersistResponse.java
> +    public static MajorPersistResponse of(Long id, String name) {
persist response에서는 식별자 값만 넘겨줘도 충분해요~

2024-10-20 23:29 UTC, LeeShinHaeng commented on aics-apis/aics-api/src/main/java/kgu/developers/apis/api/AicsApiApplication.java
> +    }
바뀌기 전 8칸에서 4칸으로 변경된것 같아요~~

2024-10-20 23:29 UTC, LeeShinHaeng commented on aics-apis/aics-api/src/main/java/kgu/developers/apis/api/major/presentation/response/MajorPersistResponse.java
> +    public static MajorPersistResponse of(Long id, String name) {
넵!!
[6336318](https://github.com/kgu-developers/aics-server/pull/22/commits/63363189a5fd6d8a8405945ef6a730f7e274eded) 에서 반영했습니다!

2024-10-21 02:39 UTC, LeeHanEum approved these changes
👍

2024-10-21 02:44 UTC, merged