Feature/#36 Post 엔티티 수정 및 게시글 작성 API 구현
kgu-developers/aics-server pull request #38
Opened 2024-10-24 14:07 UTC by minjo-on

## Summary

> close #36 

## Tasks

- post Entity category nullable = true 설정, content 타입 text 변경
- 게시글 작성 api 구현

## To Reviewer

postService에 주석으로 고민 남겨뒀는데 보시고 조언 부탁드립니다 !

2024-10-24 14:27 UTC, LeeShinHaeng reviewed
고생 많으셨어요!
다만 한가지 궁금한 점이 있어 코멘트로 남깁니다~

2024-10-24 14:27 UTC, LeeShinHaeng commented on aics-core/aics-domain/src/main/java/kgu/developers/core/domain/post/Post.java
> +
create에서 author를 바로 연결하지 않고, addPost에서 setter를 통해 연결한 이유가 있으실까요?

2024-10-24 14:39 UTC, minjo-on commented on aics-core/aics-domain/src/main/java/kgu/developers/core/domain/post/Post.java
> +
addPost 메서드를 통해 User 객체가 Post를 추가하는 동시에 Post의 author를 설정하여 두 객체 간의 관계가 완전하게 설정됩니다. 이렇게 하면 객체 간의 관계 설정을 한 곳에서 관리할 수 있어, 관계 일관성이 보장되고 코드의 유지보수성도 높아질 거라 생각했습니다. 또한, 관계의 주도권을 User가 가지기 때문에, User가 게시글을 추가할 때 자연스럽게 author를 설정하여 양방향 관계를 명확하게 유지할 수 있을거라 생각했습니다 ㅎ

2024-10-25 00:12 UTC, LeeHanEum requested changes
고민 많이 하신 흔적이 보이네요. 유익한 코드였습니다 👍
몇가지 부분만 수정 부탁드립니다!

2024-10-25 00:12 UTC, LeeHanEum commented on aics-apis/aics-api/src/main/java/kgu/developers/apis/api/post/application/PostService.java
> +		// 페치조인을 사용하면 다시 사용할 일이 있을까? 해서 이렇게 구현했슴다
많이 고민하신 부분이 보이네요 👍
일반적으로 Fetch Join은 n+1 문제를 해결하거나 조인 된 엔티티의 데이터를 즉시 가져와야할 때 사용합니다. 
현재 Post-User 엔티티간 지연로딩이 적용되어 있어서 일부 fetch join이 필요한 상황이 발생할 수도 있을 것 같습니다.
다만, 해당 메서드는 조회가 아닌 생성을 하고 있으므로 join에 대한 문제는 고려하지 않으셔도 될것 같습니다. 
추후, `부모 : 자식 = 1 : N`인 상황에서 조회 API를 구현하실 때 QueryDsl로 fetch join을 적용해보시면 좋을 것 같습니다 👍

[참고 포스팅](https://9hyuk9.tistory.com/91)

2024-10-25 00:12 UTC, LeeHanEum commented on aics-apis/aics-api/src/main/java/kgu/developers/apis/api/post/presentation/PostController.java
> +@RequestMapping("/api/v1/posts")
다른 controller를 참고해서 `@Tag`어노테이션 달아주세요

2024-10-25 00:12 UTC, LeeHanEum commented on aics-apis/aics-api/src/main/java/kgu/developers/apis/api/post/presentation/PostController.java
> +	@PostMapping
`@Operation`, `@ApiResponse`를 내부적으로 논의한 규칙에 따라 작성해주세요.
개행도 다른 controller의 컨벤션을 준수하여 주시면 감사하겠습니다.

2024-10-25 00:12 UTC, LeeHanEum commented on aics-apis/aics-api/src/main/java/kgu/developers/apis/api/post/presentation/request/PostCreateRequest.java
> +	Category category
Category는 추후 고려할 대상이므로 엔티티에서만 남겨두면 충분할것 같습니다.
아예 삭제 부탁드려요~

2024-10-25 00:12 UTC, LeeHanEum commented on aics-apis/aics-api/src/main/java/kgu/developers/apis/api/post/presentation/response/PostCreateResponse.java
> +public record PostCreateResponse(
`POST` API에서 식별자를 반환하는 용도 이므로 `PostPersistResponse`가 적절해보입니다.

2024-10-25 00:12 UTC, LeeHanEum commented on aics-apis/aics-api/src/main/java/kgu/developers/apis/api/post/presentation/response/PostCreateResponse.java
> +	@NotNull(message = "게시글이 저장되지 않았습니다.")
리스폰스에서 유효성 검증 어노테이션을 붙이신 이유가 있을까요? 
Constraint 어노테이션은 dispatcher servelt을 통해 이뤄지기 때문에 리스폰스에서는 동작하지 않습니다.

2024-10-25 00:12 UTC, LeeHanEum commented on aics-apis/aics-api/src/main/java/kgu/developers/apis/api/post/presentation/response/PostCreateResponse.java
> +	public static PostCreateResponse from(Post post) {
단순 식별자를 반환하는 용도 이므로 준영속성 객체를 매개변수로 받는 것은 불필요해 보입니다. 
of 메서드로 변경하고 Long id를 매개변수로 받는건 어떨까요?
추가적으로 저희는 모든 dto 반환 과정에서 `builder`를 사용하고 있습니다!

2024-10-25 00:12 UTC, LeeHanEum commented on aics-core/aics-domain/src/main/java/kgu/developers/core/domain/post/Post.java
> +	@Column(nullable = true)
기본값이 nullable 하니까 49번 라인 아예 삭제해주셔도 될것 같아요.

2024-10-25 00:12 UTC, LeeHanEum commented on aics-core/aics-domain/src/main/java/kgu/developers/core/domain/post/Post.java
> +
SRP 원칙에 따르면, 각 객체는 자신의 상태를 직접 관리하는 것이 원칙입니다. 
즉, Post는 Post의 생성만 관리해야 합니다. 
만약 이 정적팩토리메서드에서 `author.addPost()`를 호출하게 되면, Post 객체 생성과 동시에 User 객체의 상태를 변경하는, 
객체의 일관성을 해치는 코드라고 생각합니다.

그렇지만 `addPost`를 사용하여 두 객체 간의 관계를 완전하게 설정하는 접근은 매우 훌륭해보입니다. 👍
음 제 추천은 author와 관련된 코드를 정적팩토리메서드에서는 제거하고 서비스 레이어로 이동시키는 것은 어떨까요?

2024-10-25 00:27 UTC, minjo-on commented on aics-core/aics-domain/src/main/java/kgu/developers/core/domain/post/Post.java
> +
유저 정보 불러오는 방법을 신경쓰다보니 그렇게 하는걸 생각을 못해봤네요 좋은 방법인 것 같습니다 ㅎ

2024-10-25 00:29 UTC, minjo-on commented on aics-apis/aics-api/src/main/java/kgu/developers/apis/api/post/application/PostService.java
> +		// 페치조인을 사용하면 다시 사용할 일이 있을까? 해서 이렇게 구현했슴다
좋은 자료 감사합니다 ~~

2024-10-25 00:32 UTC, minjo-on commented on aics-apis/aics-api/src/main/java/kgu/developers/apis/api/post/presentation/PostController.java
> +	@PostMapping
넵 주의하겠습니다 !

2024-10-25 00:42 UTC, minjo-on commented on aics-apis/aics-api/src/main/java/kgu/developers/apis/api/post/presentation/response/PostCreateResponse.java
> +	@NotNull(message = "게시글이 저장되지 않았습니다.")
심신미약 상태였습니다 하하

2024-10-25 00:52 UTC, minjo-on commented on aics-apis/aics-api/src/main/java/kgu/developers/apis/api/post/presentation/response/PostCreateResponse.java
> +	public static PostCreateResponse from(Post post) {
좋은 의견 감사합니다 ㅎ

2024-10-25 01:13 UTC, LeeHanEum approved these changes
LGTM👍

2024-10-25 01:14 UTC, merged