feature/#34 파일 업로드 기능
kgu-developers/aics-server pull request #40
Opened 2024-10-25 12:34 UTC by LeeShinHaeng

## Summary

> close #34 

파일 업로드 구현

## Tasks

- FileController: 엔드포인트 (일단 FileController로 PostController와 개별적 개발)
- FileService: 비즈니스 로직 작성
- FileHandler: 파일 처리 
- 엔티티, Repository, 예외 처리

2024-10-25 14:35 UTC, LeeHanEum requested changes
디스코드에서 논의한 부분 확인해주시면 감사하겠습니다!

2024-10-25 14:35 UTC, LeeHanEum commented on aics-global-utils/src/main/java/kgu/developers/globalutils/file/FileHandler.java
> +	private static final long MAX_FILE_SIZE = 1000 * 1024 * 1024;
파일 최대 사이즈 application.yml에 명시하면 좋을 것 같습니다.

``` 
servlet:
    multipart:
        maxFileSize: 20MB
```

2024-10-25 14:35 UTC, LeeHanEum commented on aics-global-utils/src/main/java/kgu/developers/globalutils/file/FileHandler.java
> +		};
이것도 applicaiton.yml에 명시할 수 있을것 같아요

2024-10-26 04:32 UTC, LeeShinHaeng commented on aics-global-utils/src/main/java/kgu/developers/globalutils/file/FileHandler.java
> +	private static final long MAX_FILE_SIZE = 1000 * 1024 * 1024;
넵! [9fa1a2f](https://github.com/kgu-developers/aics-server/pull/40/commits/9fa1a2f5db8f0739ce067e1d12b6f15b69d609fa) 에서 반영했습니다

2024-10-26 04:33 UTC, LeeShinHaeng commented
> 디스코드에서 논의한 부분 확인해주시면 감사하겠습니다!

반영 완료했습니다! 혹시 잘못 전달된 부분이 있다면 피드백해주시길 바랍니다 😃

2024-10-26 11:21 UTC, LeeHanEum approved these changes
수고 많으셨습니다. 몇가지 점만 추가적으로 수정해주시고 바로 병합해주세요 👍

2024-10-26 11:21 UTC, LeeHanEum commented on aics-apis/aics-api/src/main/java/kgu/developers/apis/api/file/presentation/FileController.java
> +		}
try ~ catch는 비즈니스 로직의 관심사 입니다. Service로 이동하는건 어떨까요?

2024-10-26 11:21 UTC, LeeHanEum commented on aics-apis/aics-api/src/main/java/kgu/developers/apis/api/file/presentation/response/FilePersistResponse.java
> +		return new FilePersistResponse(id);
우리 프로젝트에서는 모든 리스폰스에서 builder를 사용하고 있어요~
컨벤션을 위해 builder 사용해주시면 감사하겠습니다

2024-10-26 11:21 UTC, LeeHanEum commented on aics-global-utils/src/main/java/kgu/developers/globalutils/file/FileHandler.java
> +		}
switch case 문으로 바꾸면 더 간결할것 같아요

2024-10-26 11:37 UTC, LeeShinHaeng commented on aics-apis/aics-api/src/main/java/kgu/developers/apis/api/file/presentation/FileController.java
> +		}
넵!
[b8a2236](https://github.com/kgu-developers/aics-server/pull/40/commits/b8a2236e0544663d0a892efba73587eb3847d124) 에서 반영완료했습니다!

2024-10-26 11:37 UTC, LeeShinHaeng commented on aics-apis/aics-api/src/main/java/kgu/developers/apis/api/file/presentation/response/FilePersistResponse.java
> +		return new FilePersistResponse(id);
앗 놓친 부분이 있었네요
[b8a2236](https://github.com/kgu-developers/aics-server/pull/40/commits/b8a2236e0544663d0a892efba73587eb3847d124) 에서 반영완료했습니다!

2024-10-26 11:38 UTC, LeeShinHaeng commented on aics-global-utils/src/main/java/kgu/developers/globalutils/file/FileHandler.java
> +		}
다른 메서드를 호출하는 부분이라 switch case 문을 적용하기 어렵다고 생각했습니다. 
혹시 방법이 있을까요?

2024-10-26 12:58 UTC, merged